#pragma once

//Screen dimensions
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 416
#define MAP_HEIGHT 13
#define MAP_WIDTH 16
#define GRAVITY 96.0f
#define TILE_WIDTH 32
#define TILE_HEIGHT 32
#define MOVEMENT_SPEED 150.0f
#define JUMP_FORCE_DECREMENT 400.0f
#define INITIAL_JUMP_FORCE 400.0f
#define SCREENSHAKE_DURARTION 0.25f
#define INJURED_TIME 2.5f
//#define KOOPA_SPEED 96.0f
#define SMALL_INITIAL_JUMP_FORCE 200.0f
#define ANIMATION_DELAY 20.0f